{% set version = "1.3.1" %}

package:
  name: spreg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spreg/spreg-{{ version }}.tar.gz
  sha256: 88a2766b60563fc0486f16b4bfb21e6290a5136034039df21daa68677ee1cc62

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - libpysal
    - numpy
    - scipy

test:
  imports:
    - spreg

about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: PySAL Spatial Econometrics Package

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
