{% set version = "1.4.2" %}

package:
  name: spreg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spreg/spreg-{{ version }}.tar.gz
  sha256: 68927071005daf8ddaf0d75c53f3d6438e23d2cd863f1d4eb3725ded5e7df91a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - libpysal
    - numpy >=1.23
    - scipy >=0.11

test:
  imports:
    - spreg

about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: PySAL Spatial Econometrics Package

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
    - knaaptime
    - martinfleis
