{% set version = "1.3.2" %}

package:
  name: spreg
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spreg/spreg-{{ version }}.tar.gz
  sha256: 1b6bb91916a77a450f46b8d552ff1571919f18c742be0834765b03d5bbc9931f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - libpysal
    - numpy
    - scipy

test:
  imports:
    - spreg

about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: PySAL Spatial Econometrics Package

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
